name: rihou
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: 安装依赖
        run: pip install requests
      - name: 运行脚本生成源
        run: python rihou/rihou.py
      - name: 提交并推送
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add rihou/rihou*.txt rihou/rihou*.m3u
          git add rihou.txt rihou.m3u
          git commit -m "Update"
          git push
